import XCTest
@testable import FramecraftCore

/// Fixtures generated by running the web app's TypeScript (lib/presets.ts,
/// lib/builtin-skill.ts) so the Swift port stays identical.
final class WebParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct Ratio: Decodable { let model: String; let resolution: String; let ratios: [String] }
        struct Compose: Decodable { let prompt: String; let camera: String; let film: String; let aspect: String; let result: String }
        struct Example: Decodable { let idea: String; let titles: [String] }
        let ratios: [Ratio]
        let compose: [Compose]
        let examples: [Example]
    }

    func fixture() throws -> Fixture {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "Fixtures/web-parity", withExtension: "json")
            ?? Bundle.module.url(forResource: "web-parity", withExtension: "json", subdirectory: "Fixtures"))
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    func testRatiosMatchWebApp() throws {
        for item in try fixture().ratios {
            XCTAssertEqual(Presets.ratios(model: item.model, resolution: item.resolution), item.ratios, "\(item.model) \(item.resolution)")
        }
    }

    func testComposePromptMatchesWebApp() throws {
        for item in try fixture().compose {
            let result = Presets.composePrompt(item.prompt, camera: item.camera, film: item.film, aspect: item.aspect)
            if let expected = try? JSONSerialization.jsonObject(with: Data(item.result.utf8)) as? NSDictionary {
                let actual = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(result.utf8)) as? NSDictionary, result)
                XCTAssertEqual(actual, expected, "\(item.prompt) / \(item.camera) / \(item.film) / \(item.aspect)")
            } else {
                XCTAssertEqual(result, item.result, "\(item.prompt) / \(item.camera) / \(item.film) / \(item.aspect)")
            }
        }
    }

    func testRelevantExamplesMatchWebApp() throws {
        let resources = try XCTUnwrap(SkillResources.locate(), "Skill resources not found")
        XCTAssertEqual(resources.examples.count, 123)
        for item in try fixture().examples {
            XCTAssertEqual(SkillLibrary.relevantExamples(idea: item.idea, examples: resources.examples).map(\.title), item.titles, item.idea)
        }
    }
}

final class SkillTests: XCTestCase {
    func testBuiltinsIncludeSeedanceKit() throws {
        let resources = try XCTUnwrap(SkillResources.locate())
        let skills = SkillLibrary.builtins(resources)
        XCTAssertEqual(skills.map(\.id), [SkillLibrary.jsonProfileID, SkillLibrary.ugcID, SkillLibrary.arthasID])
        let ugc = try XCTUnwrap(skills.first { $0.id == SkillLibrary.ugcID })
        XCTAssertEqual(ugc.media, .video)
        XCTAssertTrue(ugc.content.contains("Principio rector"))
        XCTAssertTrue(ugc.content.contains("PACING"), "Walter lessons should be included")
        XCTAssertFalse(ugc.content.hasPrefix("---"), "YAML front matter must be stripped")
        XCTAssertFalse(resources.jsonProfile.isEmpty)
        XCTAssertTrue(SkillLibrary.walterExample(resources).contains("BLOQUE BASE"))
        XCTAssertTrue(FileManager.default.fileExists(atPath: resources.guidePDF.path))
    }

    func testParsesFrontMatter() {
        let parsed = SkillLibrary.parse(markdown: """
        ---
        name: "mi-skill"
        description: 'Escribe prompts de video
          para Seedance.'
        ---

        # Cuerpo
        Texto.
        """, fallbackName: "x")
        XCTAssertEqual(parsed.name, "mi-skill")
        XCTAssertEqual(parsed.summary, "Escribe prompts de video para Seedance.")
        XCTAssertEqual(parsed.body, "# Cuerpo\nTexto.")
        XCTAssertEqual(SkillLibrary.guessMedia(name: parsed.name, summary: parsed.summary, body: parsed.body), .video)

        let plain = SkillLibrary.parse(markdown: "Solo texto", fallbackName: "archivo")
        XCTAssertEqual(plain.name, "archivo")
        XCTAssertEqual(plain.body, "Solo texto")
    }
}

final class LinterTests: XCTestCase {
    let good = """
    FORMAT: Vertical 9:16, 10 seconds, one continuous take, no cuts. Deep depth of field, the background is fully readable.
    0–5 s: she lifts the jar. Text in parentheses before a spoken line is acting direction only. It is NEVER spoken aloud.
    P1 (quiet, a breath before the last word): "I have been using this every single morning and my skin finally stopped fighting me."
    5–10 s: P1 (laughing, volume up): "Honestly I did not expect it to work this fast, look at this."
    Match @Audio1 for timbre, age, accent and pitch only. Do not reproduce any words from @Audio1 and do not copy its emotion.
    @Image1 is the product. No music, no text, no gimbal, no bokeh.
    """

    func testGoodPromptPasses() {
        let report = PromptLinter.lintVideo(good, duration: 10, references: .init(images: 1, audios: 1), ugcStyle: true)
        XCTAssertEqual(report.problems, 0, report.items.map(\.title).joined(separator: " | "))
        XCTAssertEqual(report.warnings, 0, report.items.filter { $0.state == .warning }.map(\.title).joined(separator: " | "))
        XCTAssertEqual(report.targetWords, 25)
    }

    func testDetectsCommonMistakes() {
        let bad = "A cinematic shot with shallow depth of field and bokeh. She says \"hi\". Use @Image3 as the start."
        let report = PromptLinter.lintVideo(bad, duration: 30, references: .init(images: 2), ugcStyle: true)
        let ids = Dictionary(uniqueKeysWithValues: report.items.map { ($0.id, $0.state) })
        XCTAssertEqual(ids["refs"], .problem)
        XCTAssertEqual(ids["timeline"], .warning)
        XCTAssertEqual(ids["dialogue"], .warning)
        XCTAssertEqual(ids["adwords"], .warning)
        XCTAssertEqual(ids["restrictions"], .warning)
    }

    func testHelpers() {
        XCTAssertTrue(PromptLinter.hasTimestamps("0–6 s: walks in"))
        XCTAssertTrue(PromptLinter.hasTimestamps("from 12-20s the camera"))
        XCTAssertTrue(PromptLinter.hasTimestamps("[00:00 - 00:03]"))
        XCTAssertFalse(PromptLinter.hasTimestamps("a 26mm lens at 1.5 m"))
        XCTAssertEqual(PromptLinter.dialogueWords(in: "He says “one two three” and \"four five\"."), 5)
        XCTAssertEqual(PromptLinter.highestTag("@Image", in: "@Image1 and @image12"), 12)
        XCTAssertFalse(PromptLinter.containsUnnegated("no gimbal, steadicam or dolly", "steadicam"))
        XCTAssertTrue(PromptLinter.containsUnnegated("a smooth gimbal shot", "gimbal"))
        XCTAssertFalse(PromptLinter.containsUnnegated("a pianolut", "lut"))
        XCTAssertEqual(DialogueMath.targetWords(seconds: 30), 74)
    }
}

final class PromptRequestTests: XCTestCase {
    func testVideoAnswerWithNotes() throws {
        let raw = "```json\n{\"prompt\": \"FORMAT: vertical\", \"notes\": \"Cargá @Image1 primero.\"}\n```"
        let result = try PromptRequests.finalize(raw, media: .video, structured: false)
        XCTAssertEqual(result, PromptResult(prompt: "FORMAT: vertical", notes: "Cargá @Image1 primero."))
        let plain = try PromptRequests.finalize("Just a prompt", media: .video, structured: false)
        XCTAssertEqual(plain.prompt, "Just a prompt")
    }

    func testMainPromptFromProfile() {
        XCTAssertEqual(PromptRequests.mainPrompt(fromProfile: "{\"generation_parameters\":{\"prompts\":[\"A waiter\"]}}"), "A waiter")
        XCTAssertNil(PromptRequests.mainPrompt(fromProfile: "Plain prompt"))
    }

    func testStructuredProfileIsValidated() throws {
        let sections = PromptRequests.profileSections.map { "\"\($0)\": {}" }.joined(separator: ",")
        XCTAssertNoThrow(try PromptRequests.finalize("{\(sections)}", media: .image, structured: true))
        XCTAssertThrowsError(try PromptRequests.finalize("{\"metadata\": {}}", media: .image, structured: true))
    }

    func testReadersAndBrief() throws {
        XCTAssertEqual(try PromptRequests.readChat(["choices": [["message": ["content": " hola "]]]]), "hola")
        XCTAssertEqual(try PromptRequests.readCodex(["output": [["content": [["type": "output_text", "text": "a"]]]]]), "a")
        XCTAssertEqual(try PromptRequests.readOpenAI(["output": [["type": "message", "content": [["type": "output_text", "text": "b"]]]]]), "b")
        XCTAssertThrowsError(try PromptRequests.readChat([:]))

        let brief = PromptBrief(idea: "idea", media: .video, targetModel: Presets.videoModelID, aspect: "9:16", resolution: "720p",
                                duration: 20, dialogueLanguage: "Español", referenceTags: ["@Image1 = a.png"])
        let json = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(PromptRequests.briefJSON(brief, skill: nil).utf8)) as? [String: Any])
        XCTAssertEqual(json["targetDialogueWords"] as? Int, 49)
        XCTAssertEqual(json["referenceTags"] as? [String], ["@Image1 = a.png"])

        let image = GenerationInputs.image(model: "gpt-image-2", finalPrompt: "p", aspect: "1:1", resolution: "1K", referenceURLs: [])
        XCTAssertEqual(image.model, "gpt-image-2-text-to-image")
        let nano = GenerationInputs.image(model: "nano-banana-pro", finalPrompt: "p", aspect: "1:1", resolution: "1K", referenceURLs: [URL(string: "https://x/y.png")!])
        XCTAssertEqual(nano.model, "nano-banana-pro")
        XCTAssertEqual(nano.input["image_input"] as? [String], ["https://x/y.png"])
    }

    func testPromptModels() throws {
        let ids = PromptRequests.promptModels.map(\.id)
        XCTAssertFalse(ids.contains { $0.hasPrefix("gemini-2.5") })
        let gemini = PromptRequests.promptModels.first { $0.id == "gemini-3.8-flash" }
        XCTAssertEqual(gemini?.api, .chat(slugs: ["gemini-3.8-flash", "gemini-3-8-flash"]))
        let claude = try XCTUnwrap(PromptRequests.promptModels.first { $0.id == "claude-opus-4-6" })
        let requests = PromptRequests.kieRequests(for: claude, instructions: "i", brief: "b", images: ["https://x/y.png"])
        XCTAssertEqual(requests.map(\.path), ["/claude/v1/messages"])
        XCTAssertEqual(requests[0].body["model"] as? String, "claude-opus-4-6")
        XCTAssertEqual(try PromptRequests.readClaude(["content": [["type": "text", "text": "hola"]]]), "hola")
        XCTAssertEqual(try PromptRequests.readChat(["code": 200, "data": ["choices": [["message": ["content": "x"]]]]]), "x")
        let gpt = try XCTUnwrap(PromptRequests.promptModels.first { $0.id == PromptRequests.defaultPromptModel })
        let terra = PromptRequests.kieRequests(for: gpt, instructions: "i", brief: "b", images: [])
        XCTAssertEqual(terra.map(\.path), ["/codex/v1/responses"])
        XCTAssertEqual(terra[0].body["model"] as? String, "gpt-5-6-terra")
        XCTAssertNotNil(terra[0].body["input"])
        let gpt52 = try XCTUnwrap(PromptRequests.promptModels.first { $0.id == "gpt-5-2" })
        XCTAssertEqual(PromptRequests.kieRequests(for: gpt52, instructions: "i", brief: "b", images: []).map(\.path), ["/gpt-5-2/v1/chat/completions"])
        let body = PromptRequests.kieChatBody(model: "gemini-3.8-flash", instructions: "i", brief: "b", images: [])
        XCTAssertEqual(body["stream"] as? Bool, true)
        XCTAssertTrue(PromptRequests.codexCLIPrompt(instructions: "I", brief: "B").hasSuffix("Creative brief:\nB"))
    }

    func testMediaSniffer() {
        XCTAssertTrue(MediaSniffer.matches(prefix: Data([137, 80, 78, 71, 13, 10, 26, 10]), mime: "image/png", kind: .image))
        XCTAssertFalse(MediaSniffer.matches(prefix: Data([0, 0, 0, 0]), mime: "image/png", kind: .image))
        XCTAssertTrue(MediaSniffer.matches(prefix: Data([0, 0, 0, 24] + Array("ftypisom".utf8)), mime: "video/mp4", kind: .video))
        XCTAssertEqual(MediaSniffer.classify(URL(fileURLWithPath: "/a/b.MOV"))?.mime, "video/quicktime")
    }
}

final class StoryTests: XCTestCase {
    func testParsesStoryAndScene() throws {
        let raw = """
        ```json
        {"title":"Walter","summary":"Un mozo de 82 años.","continuity":"BIBLE","referenceOrder":"Cargá @Image1 primero.",
         "scenes":[{"number":1,"title":"Hook","summary":"Presentación","duration":30,"prompt":"BIBLE\\n0–5 s: …","notes":"70 palabras"},
                   {"number":2,"title":"La hija","summary":"","duration":"25 s","prompt":"BIBLE 2"},
                   {"number":3,"title":"Vacía","prompt":""}]}
        ```
        """
        let draft = try StoryRequests.parseStory(raw, defaultDuration: 20)
        XCTAssertEqual(draft.title, "Walter")
        XCTAssertEqual(draft.scenes.count, 2)
        XCTAssertEqual(draft.scenes[1].duration, 25)
        XCTAssertEqual(draft.scenes[0].notes, "70 palabras")
        XCTAssertThrowsError(try StoryRequests.parseStory("no json", defaultDuration: 20))
        let scene = try StoryRequests.parseSingleScene("{\"title\":\"T\",\"summary\":\"S\",\"duration\":99,\"prompt\":\"P\"}", defaultDuration: 10)
        XCTAssertEqual(scene.duration, 30)
    }

    func testTagsAndExport() {
        let image = UUID(), audio = UUID()
        var story = Story(title: "Walter", brief: "b", slots: [
            StoryReferenceSlot(kind: .image, referenceID: image, note: "tríptico"),
            StoryReferenceSlot(kind: .audio, referenceID: audio),
            StoryReferenceSlot(kind: .image, isLastFrame: true),
        ])
        XCTAssertEqual(story.tag(for: story.slots[2]), "@Image2")
        XCTAssertEqual(story.tag(for: story.slots[1]), "@Audio1")
        let lines = StoryRequests.referenceLines(story, names: [image: "walter.png", audio: "voz.mp3"])
        XCTAssertEqual(lines[0], "@Image1 = walter.png — tríptico")
        XCTAssertTrue(lines[2].hasPrefix("@Image2 = the last frame"))
        story.scenes = [StoryScene(number: 1, title: "Hook", summary: "s", duration: 30, prompt: "PROMPT 1")]
        let text = StoryRequests.exportText(story, referenceLines: lines)
        XCTAssertTrue(text.contains("ESCENA 1 — Hook (30s)"))
        XCTAssertTrue(text.contains("PROMPT 1"))
        let brief = StoryRequests.storyBrief(story, referenceLines: lines, skill: nil, previous: true, feedback: "más corto")
        XCTAssertTrue(brief.contains("previousStory"))
        XCTAssertTrue(brief.contains("más corto"))
    }
}
